# Generated by Django 4.2.4 on 2023-09-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('PhoneNumber', models.PositiveIntegerField()),
                ('EmailID', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('DateofBirth', models.DateField()),
                ('FiveKMTime', models.TimeField()),
                ('IsAdmin', models.BooleanField(default=False)),
                ('IsTrainer', models.BooleanField(default=False)),
            ],
        ),
    ]
