# Generated by Django 4.2.4 on 2023-09-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='DateofBirth',
            new_name='dateofBirth',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='EmailID',
            new_name='emailID',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='FiveKMTime',
            new_name='fiveKMTime',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='IsAdmin',
            new_name='isAdmin',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='IsTrainer',
            new_name='isTrainer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='PhoneNumber',
            new_name='phoneNumber',
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
