# Generated by Django 4.2.4 on 2023-09-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0008_remove_trainingplans_id_trainingplans_trainingplanid'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='TrainingPlans',
            field=models.ManyToManyField(to='trainingplans.trainingplans'),
        ),
    ]
