# Generated by Django 4.2.4 on 2023-09-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_trainingplans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
