# Generated by Django 4.2.4 on 2023-09-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
