# Generated by Django 4.2.4 on 2023-09-09 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0009_alter_trainingplans_trainingplansprice'),
        ('order', '0005_alter_order_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='TrainingPlans',
        ),
        migrations.AddField(
            model_name='order',
            name='TrainingPlans',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='trainingplans.trainingplans'),
            preserve_default=False,
        ),
    ]
