# Generated by Django 4.2.4 on 2023-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0009_alter_trainingplans_trainingplansprice'),
        ('order', '0006_remove_order_trainingplans_order_trainingplans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='OrderDate',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='TrainingPlans',
        ),
        migrations.AddField(
            model_name='order',
            name='TrainingPlans',
            field=models.ManyToManyField(to='trainingplans.trainingplans'),
        ),
    ]
