# Generated by Django 4.2.4 on 2023-09-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplans',
            name='trainingsheet',
            field=models.FileField(upload_to='plans'),
        ),
    ]
