# Generated by Django 4.2.4 on 2023-09-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0002_alter_trainingplans_trainingsheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingplans',
            old_name='trainingDistance',
            new_name='trainingDurationinWeeks',
        ),
    ]
