# Generated by Django 4.2.4 on 2023-09-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0003_rename_trainingdistance_trainingplans_trainingdurationinweeks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingplans',
            old_name='trainingPackage',
            new_name='trainingPackageName',
        ),
        migrations.RemoveField(
            model_name='trainingplans',
            name='trainingsheet',
        ),
        migrations.AddField(
            model_name='trainingplans',
            name='traininglevel',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
