# Generated by Django 4.2.4 on 2023-09-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0004_rename_trainingpackage_trainingplans_trainingpackagename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplans',
            name='traininglevel',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level II'), ('3', 'Level III')], default='1', max_length=255),
        ),
    ]
