# Generated by Django 4.2.4 on 2023-09-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0005_alter_trainingplans_traininglevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingplans',
            options={'verbose_name': 'TrainingPlan', 'verbose_name_plural': 'TrainingPlans'},
        ),
    ]
