# Generated by Django 4.2.4 on 2023-09-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0006_alter_trainingplans_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplans',
            name='imageInfo',
            field=models.ImageField(default='Pranesh__Bangalore_Marathon_.xlsx', upload_to='media/'),
        ),
    ]
