# Generated by Django 4.2.4 on 2023-09-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0007_trainingplans_imageinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplans',
            name='id',
        ),
        migrations.AddField(
            model_name='trainingplans',
            name='trainingPlanID',
            field=models.PositiveIntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
