# Generated by Django 4.2.4 on 2023-09-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0008_remove_trainingplans_id_trainingplans_trainingplanid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplans',
            name='trainingPlansPrice',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
