# Generated by Django 4.2.4 on 2023-09-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0009_alter_trainingplans_trainingplansprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplans',
            name='trainingPlandDescription',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='trainingplans',
            name='imageInfo',
            field=models.ImageField(default='static/images/items/running1.jpg', upload_to='media/plans'),
        ),
    ]
