# Generated by Django 4.2.4 on 2023-09-10 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0010_trainingplans_trainingplanddescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingplans',
            old_name='trainingPlandDescription',
            new_name='trainingPlandLongDescription',
        ),
        migrations.AddField(
            model_name='trainingplans',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplans',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingplans',
            name='trainingPlandShortDescription',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
